"""The machine-local registry hub: symlinks to each repo's own registry file + a rollup.

Layout (never git-tracked; the real data lives in each repo)::

    ~/.repository_registry/
        <name>_registry.yaml -> <repo>/<name>_registry.yaml   (one symlink per repo)
        registry.yaml                          # generated rollup, never hand-edited

``workspace/registry.py`` only opens files by name inside ``registry_dir``, so pointing
it at the hub needs no changes: symlinks resolve transparently, and the rollup serves
as its aggregate fallback.
"""

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path

from .models import RegistryError, dump_yaml, load_entry, registry_filename

logger = logging.getLogger(__name__)

HUB_ENV = "DEV_STANDARDS_REGISTRY_HUB"
ROLLUP_NAME = "registry.yaml"
ROLLUP_HEADER = (
    "# GENERATED by `dev-standards registry rollup` — do not edit.\n"
    "# One entry per repo linked in this directory, sorted by repo name.\n"
)


@dataclass
class RollupResult:
    """Outcome of building the rollup."""

    text: str
    count: int
    problems: list[str] = field(default_factory=list)


def resolve_hub(override: Path | None = None) -> Path:
    """Hub directory: explicit option, then env var, then ``~/.repository_registry``."""
    if override is not None:
        return Path(override).expanduser().resolve()
    if os.environ.get(HUB_ENV):
        return Path(os.environ[HUB_ENV]).expanduser().resolve()
    return Path.home() / ".repository_registry"


def link_target(link: Path) -> Path:
    """Absolute target of a symlink, without requiring the target to exist."""
    target = Path(os.readlink(link))
    return (
        target if target.is_absolute() else Path(os.path.abspath(link.parent / target))
    )


def link_repo(hub: Path, repo_root: Path, *, force: bool = False) -> str:
    """Symlink the repo's registry file into the hub; returns the action taken."""
    repo_root = Path(repo_root).resolve()
    if not repo_root.is_dir():
        raise RegistryError(f"{repo_root} is not a directory")
    target = repo_root / registry_filename(repo_root.name)
    link = hub / target.name
    hub.mkdir(parents=True, exist_ok=True)

    action = "linked"
    if link.is_symlink():
        current = link_target(link)
        if current == target:
            return "exists"
        if not force:
            raise RegistryError(
                f"{link.name} already points to {current}; use --force to replace"
            )
        link.unlink()
        action = "relinked"
    elif link.exists():
        raise RegistryError(
            f"{link} exists and is not a symlink; refusing to replace it"
        )
    link.symlink_to(target)
    logger.debug(f"{action} {link} -> {target}")
    return action


def registry_files(hub: Path) -> list[Path]:
    """Every ``*_registry.yaml`` in the hub (symlinks or plain files), sorted."""
    if not hub.is_dir():
        return []
    return sorted(p for p in hub.iterdir() if p.name.endswith("_registry.yaml"))


def linked_repos(hub: Path) -> list[Path]:
    """Repo roots for each symlink in the hub (the repo list for ``refresh``)."""
    return [link_target(p).parent for p in registry_files(hub) if p.is_symlink()]


def build_rollup(hub: Path) -> RollupResult:
    """Read every hub file and build the aggregate list; bad files are reported."""
    entries = []
    problems: list[str] = []
    seen: set[str] = set()
    for path in registry_files(hub):
        try:
            entry = load_entry(path)  # follows symlinks; broken links raise
        except RegistryError as e:
            logger.error(f"Skipping {path.name} in rollup: {e}")
            problems.append(f"{path.name}: {e}")
            continue
        if entry.repo in seen:
            logger.warning(
                f"Duplicate repo {entry.repo!r} in {path.name}; keeping first"
            )
            problems.append(f"{path.name}: duplicate repo {entry.repo}")
            continue
        seen.add(entry.repo)
        entries.append(entry)
    entries.sort(key=lambda e: e.repo)
    body = (
        dump_yaml([e.as_dict(include_meta=False) for e in entries])
        if entries
        else "[]\n"
    )
    return RollupResult(ROLLUP_HEADER + body, len(entries), problems)


def write_rollup(hub: Path) -> tuple[bool, RollupResult]:
    """Write the rollup if its content changed; returns (changed, result)."""
    result = build_rollup(hub)
    path = hub / ROLLUP_NAME
    current = path.read_text() if path.is_file() else None
    if current == result.text:
        return False, result
    hub.mkdir(parents=True, exist_ok=True)
    path.write_text(result.text)
    return True, result
