"""Schema for a per-repo registry file (``<repo_with_underscores>_registry.yaml``).

``repo`` and ``purpose`` are the only fields any tool reads today: the workspace
repo-map consumes ``purpose`` (``workspace/registry.py``), and the rollup keys on
``repo``. The rest are reserved and must not break the dict-with-``purpose`` contract.
"""

import logging
import re
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator

logger = logging.getLogger(__name__)

_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")
FILE_HEADER = (
    "# Generated by `dev-standards registry generate` — see docs/registry-schema.md.\n"
    "# Hand edits survive until the repo's source docs change, then are overwritten.\n"
)


class RegistryError(Exception):
    """Any user-facing registry problem (bad schema, LLM failure, hub conflict)."""


def registry_filename(repo_name: str) -> str:
    """Filename for a repo's registry file; matches ``registry.lookup_purpose``."""
    return f"{repo_name.replace('-', '_')}_registry.yaml"


def _to_list(value: Any) -> Any:
    """Be lenient about LLM output: null -> [], scalar -> [scalar], numbers -> str."""
    if value is None:
        return []
    if isinstance(value, (str, int, float, bool)):
        value = [value]
    if isinstance(value, list):
        return [
            str(v) if isinstance(v, (int, float, bool)) else v
            for v in value
            if not (isinstance(v, str) and not v.strip())
        ]
    return value


class IntegrationPoints(BaseModel):
    """Where a repo touches the outside: env vars, config keys, other repos."""

    model_config = ConfigDict(extra="forbid")

    env: list[str] = Field(default_factory=list)
    config: list[str] = Field(default_factory=list)
    deps: list[str] = Field(default_factory=list)

    @field_validator("env", "config", "deps", mode="before")
    @classmethod
    def _listify(cls, v: Any) -> Any:
        return _to_list(v)


class RepoEntry(BaseModel):
    """One repo's registry entry."""

    model_config = ConfigDict(extra="forbid")

    repo: str
    purpose: str
    interfaces: list[str] = Field(default_factory=list)
    contracts: list[str] = Field(default_factory=list)
    integration_points: IntegrationPoints = Field(default_factory=IntegrationPoints)
    model_prefs: str | None = None
    generated_from: str | None = None  # generator metadata: hash of the source docs

    @field_validator("repo")
    @classmethod
    def _valid_repo(cls, v: str) -> str:
        if not _NAME_RE.match(v):
            raise ValueError(f"invalid repo name {v!r}")
        return v

    @field_validator("purpose")
    @classmethod
    def _purpose_required(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("purpose must not be empty")
        return v

    @field_validator("interfaces", "contracts", mode="before")
    @classmethod
    def _listify(cls, v: Any) -> Any:
        return _to_list(v)

    @field_validator("model_prefs", mode="before")
    @classmethod
    def _flatten_prefs(cls, v: Any) -> Any:
        if isinstance(v, list):
            return "; ".join(str(i) for i in v)
        return v

    def as_dict(self, *, include_meta: bool = True) -> dict[str, Any]:
        """Plain dict in schema order; ``include_meta=False`` drops generator fields."""
        data = self.model_dump(exclude_none=True)
        if not include_meta:
            data.pop("generated_from", None)
        return data


def dump_yaml(data: Any) -> str:
    """Deterministic YAML: schema key order, no flow-style surprises."""
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=100)


def render_entry(entry: RepoEntry) -> str:
    """Text of a per-repo registry file."""
    return FILE_HEADER + dump_yaml(entry.as_dict())


def parse_mapping(text: str, source: str) -> dict[str, Any]:
    """Parse YAML (optionally fenced, optionally a one-item list) into a dict."""
    fenced = re.search(r"```(?:ya?ml)?\s*\n(.*?)```", text, re.DOTALL)
    body = fenced.group(1) if fenced else text
    try:
        data = yaml.safe_load(body)
    except yaml.YAMLError as e:
        raise RegistryError(f"{source} is not valid YAML: {e}") from e
    if isinstance(data, list) and len(data) == 1 and isinstance(data[0], dict):
        data = data[0]  # the old ad hoc generator emitted a one-entry list
    if not isinstance(data, dict):
        raise RegistryError(
            f"{source} must be a YAML mapping, got {type(data).__name__}"
        )
    return data


def validate_entry(data: dict[str, Any], source: str) -> RepoEntry:
    """Validate a mapping against the schema, raising RegistryError on failure."""
    try:
        return RepoEntry.model_validate(data)
    except ValidationError as e:
        problems = "; ".join(
            f"{'.'.join(str(p) for p in err['loc'])}: {err['msg']}"
            for err in e.errors()
        )
        raise RegistryError(f"{source} failed schema validation: {problems}") from e


def load_entry(path: Path) -> RepoEntry:
    """Read and validate a registry file from disk."""
    try:
        text = Path(path).read_text()
    except OSError as e:
        raise RegistryError(f"Cannot read {path}: {e}") from e
    return validate_entry(parse_mapping(text, str(path)), str(path))
