#!/bin/bash
# =============================================================================
# refresh-claude.sh — Update auto-generated sections of claude.md
#
# Usage:
#   ./refresh-claude.sh [--claude-md <path>] [--dry-run]
#
# What it does:
#   1. Reads the <!-- AUTO-GENERATED: base + modules[...] --> header from claude.md
#   2. Re-fetches base.md + all listed modules from dev-standards (GitHub raw)
#   3. Replaces everything above "## Project-Specific" with fresh content
#   4. Leaves everything at and below "## Project-Specific" untouched
#
# Run from your project root, or pass --claude-md <path> explicitly.
# =============================================================================

set -euo pipefail

# --- Defaults ----------------------------------------------------------------
CLAUDE_MD="${1:-claude.md}"
DRY_RUN=false
DEV_STANDARDS_RAW_MAIN="https://raw.githubusercontent.com/pdrangeid/dev-standards/main/claude"
DEV_STANDARDS_RAW_DEV="https://raw.githubusercontent.com/pdrangeid/dev-standards/develop/claude"
DEV_STANDARDS_RAW="$DEV_STANDARDS_RAW_DEV"  # default to develop branch for latest updates
#DEV_STANDARDS_RAW="https://raw.githubusercontent.com/pdrangeid/dev-standards/main/claude"

# --- Flag parsing ------------------------------------------------------------
POSITIONAL_ARGS=()
for arg in "$@"; do
    case "$arg" in
        --dry-run)
            DRY_RUN=true
            ;;
        --claude-md)
            # handled below with shift logic — need index-aware parsing
            ;;
        *)
            POSITIONAL_ARGS+=("$arg")
            ;;
    esac
done

# Re-parse properly for --claude-md <value>
CLAUDE_MD="claude.md"
i=0
args=("$@")
while [ $i -lt ${#args[@]} ]; do
    case "${args[$i]}" in
        --claude-md)
            i=$((i+1))
            CLAUDE_MD="${args[$i]}"
            ;;
        --dry-run)
            DRY_RUN=true
            ;;
    esac
    i=$((i+1))
done

# --- Validate ----------------------------------------------------------------
if [ ! -f "$CLAUDE_MD" ]; then
    echo "❌ claude.md not found at: $CLAUDE_MD"
    echo "   Run from project root or pass --claude-md <path>"
    exit 1
fi

# --- Read the auto-gen header ------------------------------------------------
HEADER_LINE=$(head -1 "$CLAUDE_MD")

if [[ "$HEADER_LINE" != "<!-- AUTO-GENERATED:"* ]]; then
    echo "❌ $CLAUDE_MD does not start with an AUTO-GENERATED comment."
    echo "   This file was not generated by setup-project.sh, or the header was removed."
    echo "   Cannot safely refresh — aborting."
    exit 1
fi

# Extract modules list from: <!-- AUTO-GENERATED: base + modules[neo4j,live-exporter] -->
MODULES_STRING=$(echo "$HEADER_LINE" | sed -n 's/.*modules\[\([^]]*\)\].*/\1/p')

echo "============================================="
echo " refresh-claude.sh"
echo "============================================="
echo " File    : $CLAUDE_MD"
echo " Modules : ${MODULES_STRING:-none}"
[ "$DRY_RUN" = true ] && echo " Mode    : DRY RUN"
echo "============================================="
echo ""

# --- Parse modules into array ------------------------------------------------
SELECTED_MODULES=()
if [ -n "$MODULES_STRING" ]; then
    IFS=',' read -ra SELECTED_MODULES <<< "$MODULES_STRING"
fi

# --- Find the ## Project-Specific boundary -----------------------------------
BOUNDARY_LINE=$(grep -n "^## Project-Specific" "$CLAUDE_MD" | head -1 | cut -d: -f1)

if [ -z "$BOUNDARY_LINE" ]; then
    echo "❌ Could not find '## Project-Specific' section in $CLAUDE_MD"
    echo "   Cannot safely split auto-generated vs. project-specific content."
    exit 1
fi

echo "📍 Project-Specific section starts at line $BOUNDARY_LINE"

# --- Capture the Project-Specific section (line BOUNDARY_LINE onward) --------
PROJECT_SPECIFIC=$(tail -n +"$BOUNDARY_LINE" "$CLAUDE_MD")

# --- Fetch fresh content from dev-standards ----------------------------------
FETCH_FAILED=false
TMP_FILE=$(mktemp)

echo "Fetching updated standards from dev-standards..."

# Write fresh header block (preserves original module list)
cat > "$TMP_FILE" << CLAUDEHEADER
<!-- AUTO-GENERATED: base + modules[${MODULES_STRING}] -->
<!-- Do not edit above ## Project-Specific — run refresh-claude.sh to update -->
<!-- dev-standards: https://github.com/pdrangeid/dev-standards -->

CLAUDEHEADER

# Fetch base.md
if curl -fsSL "${DEV_STANDARDS_RAW}/base.md" >> "$TMP_FILE" 2>/dev/null; then
    echo "  ✅ Fetched base.md"
else
    echo "  ❌ Failed to fetch base.md from dev-standards from ${DEV_STANDARDS_RAW}"
    FETCH_FAILED=true
fi

# Fetch each module
for module in "${SELECTED_MODULES[@]}"; do
    module=$(echo "$module" | xargs)  # trim whitespace
    [ -z "$module" ] && continue
    if curl -fsSL "${DEV_STANDARDS_RAW}/modules/${module}.md" >> "$TMP_FILE" 2>/dev/null; then
        echo "  ✅ Fetched module: ${module}.md"
    else
        echo "  ⚠️  Could not fetch module: ${module}.md (check dev-standards repo)"
        FETCH_FAILED=true
    fi
done

# Append separator + preserved Project-Specific content
printf "\n---\n\n" >> "$TMP_FILE"
echo "$PROJECT_SPECIFIC" >> "$TMP_FILE"

# --- Apply or preview --------------------------------------------------------
if [ "$FETCH_FAILED" = true ]; then
    echo ""
    echo "⚠️  One or more fetches failed. Review output above."
    echo "   The temp file has been written to: $TMP_FILE"
    echo "   Inspect it before applying manually."
    exit 1
fi

if [ "$DRY_RUN" = true ]; then
    echo ""
    echo "  [DRY-RUN] Would overwrite: $CLAUDE_MD"
    echo "  [DRY-RUN] New content preview (first 30 lines):"
    head -30 "$TMP_FILE" | sed 's/^/    /'
    rm -f "$TMP_FILE"
else
    cp "$TMP_FILE" "$CLAUDE_MD"
    rm -f "$TMP_FILE"
    echo ""
    echo "✅ $CLAUDE_MD refreshed."
    echo "   Auto-generated sections updated; ## Project-Specific preserved."
fi
echo ""
